name: Delete Merged Branches on Release Merge

on:
  push:
    branches:
      - master

jobs:
  delete-merged-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Delete merged branches
        run: |
          git fetch --prune
          git checkout release/all
          git pull
          # List branches merged into release/all, excluding release/all and master
          for branch in $(git branch --merged | grep -vE '^\*|release/all|master'); do
            # Ensure the branch is not currently checked out
            git checkout master
            # Delete the branch locally
            git branch -d $branch
            # Delete the branch on the remote
            git push origin --delete $branch
          done