name: Delete Merged Branches

on:
  push:
    branches:
      - master

jobs:
  delete-merged-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Delete merged branches
        run: |
          git fetch --prune --all
          merged_branches=$(git branch --merged master | grep -v 'master$' | xargs)
          echo "Merged branches: $merged_branches"
          for branch in $merged_branches; do
            if [[ "$branch" != "release/all" ]]; then
              git push origin --delete "$branch"
              echo "Deleted branch: $branch"
            fi
          done