name: Cleanup Merged Branches on Release Merge

on:
  push:
    branches:
      - master

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensure all history is fetched
          token: ${{ secrets.ACTION_TOKEN }}
      - name: Delete merged branches in release/all
        run: |
          git fetch --prune
          echo "Branches merged into release/all:"
          git branch -r --merged release/all | grep -vE 'release/all$'
          # Loop through each branch and delete if merged into release/all, excluding release/all itself
          for branch in $(git branch -r --merged release/all | grep -vE 'release/all$'); do
            echo "Deleting branch: ${branch#origin/}"
            git push origin --delete ${branch#origin/}
          done