name: Cleanup Merged Branches

on:
  push:
    branches:
      - master

jobs:
  delete-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cleanup local merged branches
        run: |
          git branch --merged release/all | grep -v '^\*' | grep -v 'release/all' | xargs -n 1 git branch -d

      - name: Cleanup remote merged branches
        run: |
          git fetch --prune
          git branch -r --merged release/all | grep -v 'origin/release/all' | sed 's/origin\///' | xargs -n 1 -I {} git push origin --delete {}
