name: Cleanup Merged Branches

on:
  push:
    branches:
      - master

jobs:
  delete-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cleanup merged branches
        run: |
          git fetch --prune
          git for-each-ref --format='%(refname:short)' refs/heads | while read branch; do
            if [ "$branch" != "master" ] && [ "$(git merge-base --is-ancestor $branch release/all; echo $?)" -eq 0 ]; then
              git push --delete origin $branch
            fi
          done