name: Cleanup Merged Branches on Release Merge validate Token Permission

on:
  push:
    branches:
      - master

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensure all history is fetched
          token: ${{ secrets.ACTION_TOKEN }}
      - name: Fetch release/all branch explicitly
        run: git fetch origin release/all:release/all
      - name: List all remote branches
        run: git branch -r
      - name: Delete merged branches in release/all
        run: |
          git fetch --prune
          echo "Branches merged into release/all:"
          git branch -r --merged release/all || { echo "No branches to delete."; exit 0; }
          for branch in $(git branch -r --merged release/all | grep -vE 'release/all$'); do
            branch_name=${branch#origin/}
            echo "Attempting to delete branch: $branch_name"
            git push origin --delete "$branch_name" || echo "Failed to delete $branch_name. It might be protected or already deleted."
          done