name: Cleanup Merged Branches on Release Merge

on:
  push:
    branches:
      - master

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensure all history is fetched
      - name: Delete merged branches in release/all
        run: |
          # Check if release/all was merged into master
          MERGED=$(git log -1 --pretty=format:%s)
          if [[ $MERGED == *"Merge branch 'release/all' into master"* ]]; then
            # Fetch all branches
            git fetch --prune
            # Loop through each branch and delete if merged into release/all, excluding release/all itself
            for branch in $(git branch -r --merged release/all | grep -vE 'release/all$'); do
              git push origin --delete ${branch#origin/}
            done
          else
            echo "release/all was not merged into master. No branches deleted."
          fi