name: Delete Merged Branches on Release Merge

on:
  push:
    branches:
      - master

jobs:
  delete-merged-branches:
    runs-on: ubuntu-latest
    if: contains(github.event.commits[0].message, 'merge release/all into master')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Delete merged branches
        run: |
          git fetch origin release/all:release/all
          git branch --merged release/all | grep -v '^\*' | grep -v 'release/all' | grep -v 'master' | xargs -n 1 git branch -d
          git branch -r --merged release/all | grep -v 'origin/release/all' | grep -v 'origin/master' | sed 's/origin\///' | xargs -n 1 -I {} git push origin --delete {}